### ISSUE TITLE
Move to personal account

### ISSUE THREAD

**Issue by gr2m** [itaditya/background-check#82]
Hi @itaditya, we were [looking through all of Probot's repositories](https://github.com/probot/probot/issues/1022) and decided we have to reduce the maintenance overhead of the Probot team. One thing that would help us is to move some of the apps out to the account of the people who created it.

As you created the background-check app, would you mind moving it to your account?

**Comment by itaditya** [comment]
Sure, I'll do that today

**Comment by itaditya** [comment]
@gr2m done!!

**Comment by gr2m** [comment]
Thanks!
